// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer.Orm;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(QuantityMeasurementOrmDbContext))]
    partial class QuantityMeasurementOrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RepositoryLayer.Orm.Entities.QuantityMeasurementOrmEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("EqualityResult")
                        .HasColumnType("bit");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstUnitText")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("FirstValue")
                        .HasColumnType("float");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("int");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<string>("ResultUnitText")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("ResultValue")
                        .HasColumnType("float");

                    b.Property<double?>("ScalarResult")
                        .HasColumnType("float");

                    b.Property<string>("SecondUnitText")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("SecondValue")
                        .HasColumnType("float");

                    b.Property<string>("TargetUnitText")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementType");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("OperationType");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("QuantityMeasurementOperations", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
